export const INITIALIZE = "INITIALIZE";

export const DELETE_DATA = "DELETE_DATA";

export const START_ADD_DATA = "START_ADD_DATA";
export const FINISH_ADD_DATA = "FINISH_ADD_DATA";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const CHANGE_MONTH_YEAR = "CHANGE_MONTH_YEAR";

export const CHANGE_CURRENT_DATE = "CHANGE_CURRENT_DATE";

export const SET_PROFIT = "SET_PROFIT";
